Return copies of objects, add double linked list
SergKostarev/java-kanban pull request #2
Opened 2024-06-13 19:14 UTC by SergKostarev

Новая логика добавления, получения и обновления задач из менеджера - теперь для этих целей формируются копии объектов. Добавлен двунаправленный связный список для хранения истории. Рефакторинг тестов.

2024-06-14 19:00 UTC, z8q requested changes

2024-06-15 06:51 UTC, SergKostarev commented on src/service/InMemoryHistoryManager.java
> +    HashMap<Integer, Node> taskHistory = new HashMap<>();
Сделано

2024-06-15 06:51 UTC, SergKostarev commented on src/service/InMemoryHistoryManager.java
> +    public void removeNode(Node node) {
Сделано

2024-06-15 18:34 UTC, z8q approved these changes

2024-06-25 18:30 UTC, merged