Add FileBackedTaskManager
SergKostarev/java-kanban pull request #3
Opened 2024-06-27 20:29 UTC by SergKostarev

Add FileBackedManager and tests

2024-06-28 20:13 UTC, z8q requested changes

2024-06-28 20:13 UTC, z8q commented on src/service/FileBackedTaskManager.java
> +        } else if (task.getClass() == Subtask.class) {
Две проверки на Subtask.class, тут и в 67-й строке,
можно попробовать как-нибудь оптимизировать, if/else блок внизу убрать (строки 67-77)

2024-06-29 14:42 UTC, SergKostarev commented on src/service/FileBackedTaskManager.java
> +        } else if (task.getClass() == Subtask.class) {
Сделал.

2024-06-29 14:42 UTC, SergKostarev commented on src/service/FileBackedTaskManager.java
> +    private static Task fromString(String value) {
Сделал.

2024-06-29 14:48 UTC, SergKostarev commented
Также доработал логику создания объекта FileBackedTaskManager. При десериализации задач из файла теперь обновляется idCounter, чтобы впоследствии при добавлении новых задач не возникало дублирования идентификаторов. При создании Epic из файла добавил ссылки на Subtask'и , чтобы структура задач везде была идентичной. Вынес перечисление с типами задач в отдельный класс.

2024-06-30 11:17 UTC, z8q approved these changes

2024-07-07 08:52 UTC, merged