Add time logics, refactor tests
SergKostarev/java-kanban pull request #4
Opened 2024-07-14 05:16 UTC by SergKostarev

2024-07-14 11:36 UTC, z8q requested changes

2024-07-14 11:36 UTC, z8q commented on src/service/InMemoryTaskManager.java
> +                        .map(Task::getEndTime)
Нам нужно найти самое раннее startTime и самое позднее endTime,
Сейчас набор идет из списка, который сортируется по startTime, поэтому код в строках 405-409 вероятно выполнится правильно. 
Но для endTime мы получается просто возьмем первый элемент

2024-07-14 11:36 UTC, z8q commented on src/service/InMemoryTaskManager.java
>          Epic newEpic = new Epic(epicInput);
Для метода updateEpic еще посмотрел, похоже например можно 
взять два эпика, 
заполнить их списки одинаковыми саб-тасками
и отправить в этот метод updateEpic
В менеджере в итоге будут саб-таски, которые привязаны к нескольким эпикам.

Как вариант, можно упростить метод, сделать возможным обновления только полей name и description у эпика.
Взаимодействие со списками под-задач эпика можно осуществлять только в методах, которые с ними связаны, addSubTask, deleteSubTask и т.д.

2024-07-14 11:36 UTC, z8q commented on test/service/FileBackedTaskManagerTest.java
>      @BeforeEach
Все таки стоит в одном классе использовать один метод BeforeEach, потому что порядок выполнения для нескольких таких методов не гарантируется

2024-07-14 11:36 UTC, z8q commented on test/service/FileBackedTaskManagerTest.java
> +        tm.addTask(new Task("Закончить пятый спринт", "Нет описания", TaskStatus.NEW,
Логику создания тасок можно вынести в абстрактный класс в метод initTasks(), а вызывать тут и в InMemoryTaskManagerTest, чтобы было видно, что набор тасок не отличается

2024-07-14 11:36 UTC, z8q commented on test/service/TaskManagerTest.java
> +    public void epicStatusShouldBeDone() {
Еще можно проверить, что будет со статусом эпика, если удаляем саб-таску (Например были Done и InProgress, а осталась только InProgress) или если удаляем все саб-таски

2024-07-15 17:49 UTC, SergKostarev commented on test/service/FileBackedTaskManagerTest.java
>      @BeforeEach
Исправил

2024-07-15 18:02 UTC, SergKostarev commented on test/service/TaskManagerTest.java
> +    public void epicStatusShouldBeDone() {
Исправил

2024-07-15 18:23 UTC, SergKostarev commented on src/service/InMemoryTaskManager.java
>          Epic newEpic = new Epic(epicInput);
Исправил

2024-07-15 19:35 UTC, SergKostarev commented on src/service/InMemoryTaskManager.java
> +                .toList();
Исправил, переделал логику этого метода

2024-07-15 19:35 UTC, SergKostarev commented on src/service/InMemoryTaskManager.java
> +                        .map(Task::getEndTime)
Исправил, переделал логику этого метода

2024-07-16 17:38 UTC, z8q approved these changes

2024-07-16 17:38 UTC, z8q commented on src/service/TaskManager.java
> +    Epic updateEpic(Integer epicId, String name, String description);
В предыдущих домашках где-то было требование, что в методы add/update/delete нужно передавать таску одним аргументом. То есть в нашем случае принимаем эпик и работаем с его id, name, description уже внутри метода

но это больше пожелание, можно поправить в следующей домашке

2024-07-25 18:54 UTC, merged