Add http server API
SergKostarev/java-kanban pull request #5
Opened 2024-07-28 12:12 UTC by SergKostarev

Add API & tests

2024-07-29 18:08 UTC, z8q requested changes

2024-07-29 18:08 UTC, z8q commented on test/service/HttpTaskManagerSubtasksTest.java
> +    public HttpTaskManagerSubtasksTest() throws IOException {
можно убрать

2024-07-29 18:08 UTC, z8q commented on test/service/HttpTaskManagerTasksTest.java
> +    public HttpTaskManagerTasksTest() throws IOException {
тоже можно убрать

2024-07-29 18:08 UTC, z8q commented on test/service/HttpTaskManagerTest.java
> +    public HttpTaskManagerTest() throws IOException {
можно убрать

2024-07-30 17:04 UTC, SergKostarev commented on src/service/HttpTaskServer.java
> +                .create();
Исправил

2024-07-30 17:19 UTC, SergKostarev commented on src/handler/BaseHttpHandler.java
> +        headers.set("Content-Type", "application/json; charset=utf-8");
Исправил

2024-07-30 17:25 UTC, SergKostarev commented on src/handler/BaseHttpHandler.java
> +        exchange.sendResponseHeaders(statusCode, 0);
Исправил

2024-07-30 17:27 UTC, SergKostarev commented on src/handler/BaseHttpHandler.java
> +        try (OutputStream os = exchange.getResponseBody()) {
Исправил

2024-07-30 17:38 UTC, SergKostarev commented on src/handler/BaseHttpHandler.java
> +        errorDTO.getDetails().put(exception.getMessage(), exception.getId());
Исправил

2024-07-30 17:41 UTC, SergKostarev commented on src/handler/BaseHttpHandler.java
> +        sendResponse(exchange, "Объект не найден", statusCode);
Исправил

2024-07-30 17:45 UTC, SergKostarev commented on src/handler/BaseHttpHandler.java
> +        errorDTO.getDetails().put("Эндпойнт не существует", null);
Исправил

2024-07-30 18:32 UTC, SergKostarev commented on src/handler/EpicHandler.java
> +                super.sendText(exchange, gson.toJson(epic), 200);
Исправил

2024-07-30 18:32 UTC, SergKostarev commented on src/handler/EpicHandler.java
> +                List<Subtask> epic = super.taskManager.getEpicSubtasks(id);
Исправил

2024-07-30 18:46 UTC, SergKostarev commented on test/service/HttpTaskManagerSubtasksTest.java
> +    public HttpTaskManagerSubtasksTest() throws IOException {
Не совсем понял последние три замечания. Нужно убрать конструкторы с IOException?
Перенес инициализацию полей taskServer и gson в метод setUp(), чтобы это стало возможным.

2024-07-31 16:22 UTC, z8q commented on test/service/HttpTaskManagerSubtasksTest.java
> +    public HttpTaskManagerSubtasksTest() throws IOException {
сорри, тут не обратил внимания на throws IOException

2024-07-31 16:33 UTC, z8q approved these changes

2024-07-31 16:33 UTC, z8q commented on test/service/HttpTaskManagerEpicsTest.java
> +        List<Epic> taskListDeserialized = gson.fromJson(response.body(), new EpicTypeToken().getType());
как вариант, можно приводить к типу List создавая экземпляр TypeToken прямо тут
```JAVA
List<Epic> taskListDeserialized = gson.fromJson(
    response.body(),
    new TypeToken<List<Epic>>() {}.getType()
);
```

2024-08-09 05:01 UTC, merged